var events = {
  TODO_CREATE: 'TODO_CREATE',
  TODO_COMPLETE: 'TODO_COMPLETE',
  TODO_DESTROY: 'TODO_DESTROY',
  TODO_UNDO_COMPLETE: 'TODO_UNDO_COMPLETE',
  TODO_UPDATE_TEXT: 'TODO_UPDATE_TEXT'
};
module.exports = events;
